version: '3.8'  # Specify the version if not already set

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Improves file watching in Docker
    depends_on:
      - mongo

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Improves file watching in Docker
    depends_on:
      - mongo

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: yarn start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Improves file watching in Docker
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
