apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  ports:
  - name: "tcp"
    port: 3002
    #the protocol here is TCP because inside the cluster all communication occurs via TCP
    #i.e. this service communicates with its pod via TCP (i.e. it routes the traffic from its port 3002 to the port 3002 on the pod using TCP)
    protocol: TCP
    targetPort: 3002
  - name: "http"
    port: 3003
    #the protocol here is TCP because inside the cluster all communication occurs via TCP
    #i.e. this service communicates with its pod via TCP (i.e. it routes the traffic from its port 3003 to the port 3003 on the pod using TCP)
    protocol: TCP
    targetPort: 3003
  selector:
    app: auth
  type: ClusterIP

